# Builds TbhPresence.exe from src\*.cs using the C# compiler that ships with
# Windows (.NET Framework 4.x) - no SDK install needed.
#   .\build.ps1                 # version 1.0.0 (dev default)
#   .\build.ps1 -Version 1.2.3  # stamp a specific version into the exe
param([string]$Version = '1.0.0')

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$csc = "$env:WINDIR\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) { throw "csc.exe not found at $csc" }

# normalize to a 4-part numeric version for the file-version fields
$Version = $Version.TrimStart('v')
$m = [regex]::Match($Version, '^\d+(\.\d+){0,3}')
if (-not $m.Success) { throw "invalid version: $Version" }
$numeric = $m.Value
while (($numeric -split '\.').Count -lt 4) { $numeric += '.0' }

$verFile = Join-Path $here 'src\Version.g.cs'
@"
// Generated by build.ps1 - do not edit.
using System.Reflection;
[assembly: AssemblyVersion("$numeric")]
[assembly: AssemblyFileVersion("$numeric")]
[assembly: AssemblyInformationalVersion("$Version")]
"@ | Set-Content -Path $verFile -Encoding utf8

try {
    $out = Join-Path $here 'TbhPresence.exe'
    # embed the auto-synthesis BepInEx plugin when it has been built, so the exe
    # can deploy it into the game's BepInEx\plugins folder on startup
    $synthDll = Join-Path $here 'autosynth\bin\Release\TbhAutoSynth.dll'
    $resArgs = @()
    if (Test-Path $synthDll) { $resArgs += "/res:$synthDll,TbhAutoSynth.dll" }
    else { Write-Host "note: $synthDll not found - building without the embedded autosynth plugin" -ForegroundColor Yellow }
    # /target:winexe -> no console window in tray mode (console modes attach on demand)
    & $csc /nologo /optimize+ /target:winexe /platform:anycpu `
        /out:$out `
        "/win32icon:$(Join-Path $here 'assets\app.ico')" `
        /r:System.Web.Extensions.dll `
        /r:System.Windows.Forms.dll `
        /r:System.Drawing.dll `
        @resArgs `
        (Join-Path $here 'src\*.cs')
    if ($LASTEXITCODE -ne 0) { throw "build failed" }
}
finally {
    Remove-Item $verFile -ErrorAction SilentlyContinue
}
Write-Host "Built $out (version $numeric)" -ForegroundColor Green
