# Builds TbhCompanion.exe from src\*.cs using the C# compiler that ships with
# Windows (.NET Framework 4.x) - no SDK install needed.
#   .\build.ps1                 # version 1.0.0 (dev default)
#   .\build.ps1 -Version 1.2.3  # stamp a specific version into the exe
param([string]$Version = '1.0.0')

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$csc = "$env:WINDIR\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) { throw "csc.exe not found at $csc" }

# normalize to a 4-part numeric version for the file-version fields
$Version = $Version.TrimStart('v')
$m = [regex]::Match($Version, '^\d+(\.\d+){0,3}')
if (-not $m.Success) { throw "invalid version: $Version" }
$numeric = $m.Value
while (($numeric -split '\.').Count -lt 4) { $numeric += '.0' }

$verFile = Join-Path $here 'src\Version.g.cs'
@"
// Generated by build.ps1 - do not edit.
using System.Reflection;
[assembly: AssemblyVersion("$numeric")]
[assembly: AssemblyFileVersion("$numeric")]
[assembly: AssemblyInformationalVersion("$Version")]
"@ | Set-Content -Path $verFile -Encoding utf8

# The auto-synthesis BepInEx plugin is embedded (as a resource) into the full
# edition only, so the exe can deploy it into BepInEx\plugins at runtime. Prefer
# a fresh local build; fall back to the committed prebuilt copy (the plugin can't
# be built in CI, which lacks the game-generated interop assemblies).
$synthDll = Join-Path $here 'autosynth\bin\Release\TbhAutoSynth.dll'
if (-not (Test-Path $synthDll)) { $synthDll = Join-Path $here 'autosynth\prebuilt\TbhAutoSynth.dll' }

function Build-Edition([string]$outName, [bool]$full) {
    $out = Join-Path $here $outName
    $extra = @()
    if ($full) {
        if (Test-Path $synthDll) { $extra += "/res:$synthDll,TbhAutoSynth.dll" }
        else { Write-Host "note: TbhAutoSynth.dll not found - full build without the embedded plugin" -ForegroundColor Yellow }
    } else {
        $extra += "/define:PRESENCE_ONLY"
    }
    # /target:winexe -> no console window in tray mode (console modes attach on demand)
    & $csc /nologo /optimize+ /target:winexe /platform:anycpu `
        /out:$out `
        "/win32icon:$(Join-Path $here 'assets\app.ico')" `
        /r:System.Web.Extensions.dll `
        /r:System.Windows.Forms.dll `
        /r:System.Drawing.dll `
        /r:System.IO.Compression.dll `
        /r:System.IO.Compression.FileSystem.dll `
        @extra `
        (Join-Path $here 'src\*.cs')
    if ($LASTEXITCODE -ne 0) { throw "build failed: $outName" }
    Write-Host "Built $out (version $numeric)" -ForegroundColor Green
}

try {
    Build-Edition 'TbhCompanion.exe' $true            # presence + auto-synthesis
    Build-Edition 'TbhCompanion-Presence.exe' $false  # presence only
}
finally {
    Remove-Item $verFile -ErrorAction SilentlyContinue
}
